# -*- coding: utf-8 -*-

from django.utils.translation import ugettext_lazy as _

COUNTRY_CHOICES_ONLY_BELGIUM = (
    ('BE', _(u'Belgium')),
)

COUNTRY_CHOICES = (
    ('AF', _(u'Afghanistan')),
    ('AL', _(u'Albania')),
    ('DZ', _(u'Algeria')),
    ('AS', _(u'American Samoa')),
    ('AD', _(u'Andorra')),
    ('AG', _(u'Angola')),
    ('AI', _(u'Anguilla')),
    ('AG', _(u'Antigua & Barbuda')),
    ('AR', _(u'Argentina')),
    ('AA', _(u'Armenia')),
    ('AW', _(u'Aruba')),
    ('AU', _(u'Australia')),
    ('AT', _(u'Austria')),
    ('AZ', _(u'Azerbaijan')),
    ('BS', _(u'Bahamas')),
    ('BH', _(u'Bahrain')),
    ('BD', _(u'Bangladesh')),
    ('BB', _(u'Barbados')),
    ('BY', _(u'Belarus')),
    ('BE', _(u'Belgium')),
    ('BZ', _(u'Belize')),
    ('BJ', _(u'Benin')),
    ('BM', _(u'Bermuda')),
    ('BT', _(u'Bhutan')),
    ('BO', _(u'Bolivia')),
    ('BL', _(u'Bonaire')),
    ('BA', _(u'Bosnia & Herzegovina')),
    ('BW', _(u'Botswana')),
    ('BR', _(u'Brazil')),
    ('BC', _(u'British Indian Ocean Ter')),
    ('BN', _(u'Brunei')),
    ('BG', _(u'Bulgaria')),
    ('BF', _(u'Burkina Faso')),
    ('BI', _(u'Burundi')),
    ('KH', _(u'Cambodia')),
    ('CM', _(u'Cameroon')),
    ('CA', _(u'Canada')),
    ('IC', _(u'Canary Islands')),
    ('CV', _(u'Cape Verde')),
    ('KY', _(u'Cayman Islands')),
    ('CF', _(u'Central African Republic')),
    ('TD', _(u'Chad')),
    ('CD', _(u'Channel Islands')),
    ('CL', _(u'Chile')),
    ('CN', _(u'China')),
    ('CI', _(u'Christmas Island')),
    ('CS', _(u'Cocos Island')),
    ('CO', _(u'Colombia')),
    ('CC', _(u'Comoros')),
    ('CG', _(u'Congo')),
    ('CK', _(u'Cook Islands')),
    ('CR', _(u'Costa Rica')),
    ('CT', _(u"Côte D'Ivoire")),
    ('HR', _(u'Croatia')),
    ('CU', _(u'Cuba')),
    ('CB', _(u'Curaçao')),
    ('CY', _(u'Cyprus')),
    ('CZ', _(u'Czech Republic')),
    ('DK', _(u'Denmark')),
    ('DJ', _(u'Djibouti')),
    ('DM', _(u'Dominica')),
    ('DO', _(u'Dominican Republic')),
    ('TM', _(u'East Timor')),
    ('EC', _(u'Ecuador')),
    ('EG', _(u'Egypt')),
    ('SV', _(u'El Salvador')),
    ('GQ', _(u'Equatorial Guinea')),
    ('ER', _(u'Eritrea')),
    ('EE', _(u'Estonia')),
    ('ET', _(u'Ethiopia')),
    ('FA', _(u'Falkland Islands')),
    ('FO', _(u'Faroe Islands')),
    ('FJ', _(u'Fiji')),
    ('FI', _(u'Finland')),
    ('FR', _(u'France')),
    ('GF', _(u'French Guiana')),
    ('PF', _(u'French Polynesia')),
    ('FS', _(u'French Southern Ter')),
    ('GA', _(u'Gabon')),
    ('GM', _(u'Gambia')),
    ('GE', _(u'Georgia')),
    ('DE', _(u'Germany')),
    ('GH', _(u'Ghana')),
    ('GI', _(u'Gibraltar')),
    ('GB', _(u'Great Britain')),
    ('GR', _(u'Greece')),
    ('GL', _(u'Greenland')),
    ('GD', _(u'Grenada')),
    ('GP', _(u'Guadeloupe')),
    ('GU', _(u'Guam')),
    ('GT', _(u'Guatemala')),
    ('GN', _(u'Guinea')),
    ('GY', _(u'Guyana')),
    ('HT', _(u'Haiti')),
    ('HW', _(u'Hawaii')),
    ('HN', _(u'Honduras')),
    ('HK', _(u'Hong Kong')),
    ('HU', _(u'Hungary')),
    ('IS', _(u'Iceland')),
    ('IN', _(u'India')),
    ('ID', _(u'Indonesia')),
    ('IA', _(u'Iran')),
    ('IQ', _(u'Iraq')),
    ('IR', _(u'Ireland')),
    ('IM', _(u'Isle of Man')),
    ('IL', _(u'Israel')),
    ('IT', _(u'Italy')),
    ('JM', _(u'Jamaica')),
    ('JP', _(u'Japan')),
    ('JO', _(u'Jordan')),
    ('KZ', _(u'Kazakhstan')),
    ('KE', _(u'Kenya')),
    ('KI', _(u'Kiribati')),
    ('NK', _(u'Korea North')),
    ('KS', _(u'Korea South')),
    ('KW', _(u'Kuwait')),
    ('KG', _(u'Kyrgyzstan')),
    ('LA', _(u'Laos')),
    ('LV', _(u'Latvia')),
    ('LB', _(u'Lebanon')),
    ('LS', _(u'Lesotho')),
    ('LR', _(u'Liberia')),
    ('LY', _(u'Libya')),
    ('LI', _(u'Liechtenstein')),
    ('LT', _(u'Lithuania')),
    ('LU', _(u'Luxembourg')),
    ('MO', _(u'Macau')),
    ('MK', _(u'Macedonia')),
    ('MG', _(u'Madagascar')),
    ('MY', _(u'Malaysia')),
    ('MW', _(u'Malawi')),
    ('MV', _(u'Maldives')),
    ('ML', _(u'Mali')),
    ('MT', _(u'Malta')),
    ('MH', _(u'Marshall Islands')),
    ('MQ', _(u'Martinique')),
    ('MR', _(u'Mauritania')),
    ('MU', _(u'Mauritius')),
    ('ME', _(u'Mayotte')),
    ('MX', _(u'Mexico')),
    ('MI', _(u'Midway Islands')),
    ('MD', _(u'Moldova')),
    ('MC', _(u'Monaco')),
    ('MN', _(u'Mongolia')),
    ('MS', _(u'Montserrat')),
    ('MA', _(u'Morocco')),
    ('MZ', _(u'Mozambique')),
    ('MM', _(u'Myanmar')),
    ('NA', _(u'Namibia')),
    ('NU', _(u'Nauru')),
    ('NP', _(u'Nepal')),
    ('AN', _(u'Netherland Antilles')),
    ('NL', _(u'Netherlands')),
    ('NV', _(u'Nevis')),
    ('NC', _(u'New Caledonia')),
    ('NZ', _(u'New Zealand')),
    ('NI', _(u'Nicaragua')),
    ('NE', _(u'Niger')),
    ('NG', _(u'Nigeria')),
    ('NW', _(u'Niue')),
    ('NF', _(u'Norfolk Island')),
    ('NO', _(u'Norway')),
    ('OM', _(u'Oman')),
    ('PK', _(u'Pakistan')),
    ('PW', _(u'Palau Island')),
    ('PS', _(u'Palestine')),
    ('PA', _(u'Panama')),
    ('PG', _(u'Papua New Guinea')),
    ('PY', _(u'Paraguay')),
    ('PE', _(u'Peru')),
    ('PH', _(u'Philippines')),
    ('PO', _(u'Pitcairn Island')),
    ('PL', _(u'Poland')),
    ('PT', _(u'Portugal')),
    ('PR', _(u'Puerto Rico')),
    ('QA', _(u'Qatar')),
    ('RE', _(u'Reunion')),
    ('RO', _(u'Romania')),
    ('RU', _(u'Russia')),
    ('RW', _(u'Rwanda')),
    ('NT', _(u'St Barthélemy')),
    ('EU', _(u'St Eustatius')),
    ('HE', _(u'St Helena')),
    ('KN', _(u'St Kitts-Nevis')),
    ('LC', _(u'St Lucia')),
    ('MB', _(u'St Maarten')),
    ('PM', _(u'St Pierre & Miquelon')),
    ('VC', _(u'St Vincent & Grenadines')),
    ('SP', _(u'Saipan')),
    ('SO', _(u'Samoa')),
    ('AS', _(u'Samoa American')),
    ('SM', _(u'San Marino')),
    ('ST', _(u'Sao Tome & Principe')),
    ('SA', _(u'Saudi Arabia')),
    ('SN', _(u'Senegal')),
    ('SC', _(u'Seychelles')),
    ('SS', _(u'Serbia & Montenegro')),
    ('SL', _(u'Sierra Leone')),
    ('SG', _(u'Singapore')),
    ('SK', _(u'Slovakia')),
    ('SI', _(u'Slovenia')),
    ('SB', _(u'Solomon Islands')),
    ('OI', _(u'Somalia')),
    ('ZA', _(u'South Africa')),
    ('ES', _(u'Spain')),
    ('LK', _(u'Sri Lanka')),
    ('SD', _(u'Sudan')),
    ('SR', _(u'Suriname')),
    ('SZ', _(u'Swaziland')),
    ('SE', _(u'Sweden')),
    ('CH', _(u'Switzerland')),
    ('SY', _(u'Syria')),
    ('TA', _(u'Tahiti')),
    ('TW', _(u'Taiwan')),
    ('TJ', _(u'Tajikistan')),
    ('TZ', _(u'Tanzania')),
    ('TH', _(u'Thailand')),
    ('TG', _(u'Togo')),
    ('TK', _(u'Tokelau')),
    ('TO', _(u'Tonga')),
    ('TT', _(u'Trinidad & Tobago')),
    ('TN', _(u'Tunisia')),
    ('TR', _(u'Turkey')),
    ('TU', _(u'Turkmenistan')),
    ('TC', _(u'Turks & Caicos Is')),
    ('TV', _(u'Tuvalu')),
    ('UG', _(u'Uganda')),
    ('UA', _(u'Ukraine')),
    ('AE', _(u'United Arab Emirates')),
    ('GB', _(u'United Kingdom')),
    ('US', _(u'United States of America')),
    ('UY', _(u'Uruguay')),
    ('UZ', _(u'Uzbekistan')),
    ('VU', _(u'Vanuatu')),
    ('VS', _(u'Vatican City State')),
    ('VE', _(u'Venezuela')),
    ('VN', _(u'Vietnam')),
    ('VB', _(u'Virgin Islands (Brit)')),
    ('VA', _(u'Virgin Islands (USA)')),
    ('WK', _(u'Wake Island')),
    ('WF', _(u'Wallis & Futana Is')),
    ('YE', _(u'Yemen')),
    ('ZR', _(u'Zaire')),
    ('ZM', _(u'Zambia')),
    ('ZW', _(u'Zimbabwe')),
)

EUROPEAN_COUNTRY_CHOICES = (
    ('AT', _(u'Austria')),
    ('BE', _(u'Belgium')),
    ('DE', _(u'Germany')),
    ('BG', _(u'Bulgaria')),
    ('CY', _(u'Cyprus')),
    ('DK', _(u'Denmark')),
    ('CZ', _(u'Czech Republic')),
    ('EE', _(u'Estonia')),
    ('FI', _(u'Finland')),
    ('FR', _(u'France')),
    ('GB', _(u'Great Britain')),
    ('GR', _(u'Greece')),
    ('HU', _(u'Hungary')),
    ('IR', _(u'Ireland')),
    ('IT', _(u'Italy')),
    ('LV', _(u'Latvia')),
    ('LT', _(u'Lithuania')),
    ('LU', _(u'Luxembourg')),
    ('MT', _(u'Malta')),
    ('NL', _(u'Netherlands')),
    ('PL', _(u'Poland')),
    ('PT', _(u'Portugal')),
    ('RO', _(u'Romania')),
    ('SK', _(u'Slovakia')),
    ('SI', _(u'Slovenia')),
    ('ES', _(u'Spain')),
    ('SE', _(u'Sweden')),
)
